# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# right aligned navbar item
[[main_right]]
  name = "<i class=\"ai ai-cv\" style=\"font-size: 1rem; line-height: 1.25\"></i>"
  # post = ""
  url = "https://drive.google.com/file/d/1R8E55nRruEB4GlXyERxjUZEqrFx4F9se/view?usp=sharing"
  weight = 10

[[main_right]]
  name = "<i class=\"ai ai-google-scholar\" style=\"font-size: 1rem; line-height: 1.25\"></i>"
  url = "https://scholar.google.com/citations?user=9K2O0TUAAAAJ&hl=en"
  weight = 20

[[main_right]]
  name = "<i class=\"fab fa-github\" style=\"font-size: 1rem; line-height: 1.25\"></i>"
  url = "https://github.com/elony314"
  weight = 30

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
